#!/bin/sh -e

die() {
	echo $1 1>&2
	exit 1
}

[ -f node_modules/.bin/browserify ] || npm update
mkdir -p target
cp src/index.tmpl target/index.tmpl
node_modules/.bin/browserify src/minibikemaps.js -o target/minibikemaps.js

cp index.cgi fetchmerge.cgi straviz.ini target

jshint src/*.js test/spec/*.js 
