#!/bin/sh -e

if [ -z "$1" ]; then
	echo Usage: $0 scp-dest 1>&2
	exit 1
fi

scpdest=$1
sshdest=$(echo "$scpdest" | sed 's/:.*//')
destdir=$(echo "$scpdest" | sed 's/.*://')

cd target
chmod 600 cgi-bin/straviz.json
scp -r . "$scpdest"
cd ..
scp requirements.txt "$scpdest"
ssh "$sshdest" "cd \"$destdir\" && pip3 install -r requirements.txt -t lib"
