#!/bin/sh -e

scpdest=`./get-deploy-dest`
sshdest=$(echo "$scpdest" | sed 's/:.*//')
destdir=$(echo "$scpdest" | sed 's/.*://')

echo Deploying to $scpdest
cd target
chmod 600 straviz.ini
scp -r . "$scpdest"
cd ..
scp requirements.txt "$scpdest"
ssh "$sshdest" "cd \"$destdir\" && pip3 install -r requirements.txt -t lib"
