#!/bin/bash
set -eu

if [ $# -ne 1 ]; then
	echo "Usage: $0 activity-url" 1>&2
	exit 1
fi

activity_id=$(echo "$1" | sed 's/.*activity=//')
dest="${activity_id}.png"
url="${1}&view=thumbnail"

node_modules/.bin/phantomjs rasterize.js "$url" "$dest"
echo "Thumbnail was written to $dest"
