#!/usr/bin/env python3

import os
import sys
import urllib.parse
import subprocess


if len(sys.argv) != 2:
	sys.stderr.write("Usage: %s activity-url]\n" % sys.argv[0])
	exit(1)

url = sys.argv[1]
path = urllib.parse.urlparse(url).path
activity_id = os.path.basename(path)

url += "?view=thumbnail"
dest = "target/thumbs/%s.png" % activity_id
subprocess.run(["node_modules/.bin/phantomjs", "rasterize.js", url, dest], check=True)
print("Wrote thumbnail to %s" % dest)
