#!/usr/bin/env python3

import sys
import urllib.parse
import subprocess
import tempfile
import configparser

def deploy_dest():
	config = configparser.ConfigParser()
	config.read("straviz.ini")
	return config.get("straviz", "deploy_dest")


if len(sys.argv) != 2:
	sys.stderr.write("Usage: %s activity-url\n" % sys.argv[0])
	exit(1)

url = sys.argv[1]
qs = urllib.parse.urlparse(url).query

try:
	activity_id = urllib.parse.parse_qs(qs)['activity'][0]
except KeyError:
	sys.stderr.write("Couldn't find an activity parameter in url: %s\n" % url)
	exit(1)

src = "target/thumbs/%s.png" % activity_id
subprocess.run(["./generate-thumbnail", url], check=True)
subprocess.run(["chmod", "644", src])
dest = "%s/thumbs/%s.png" % (deploy_dest(), activity_id)
subprocess.run(["scp", "-p", src, dest], check=True)
